import type { Metadata } from "next";
import {  Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen">
          {/* Sidebar */}
          <aside className="w-64 bg-gray-800 text-white p-4">
            <h1 className="text-xl font-bold mb-6">Hypesoft</h1>
            <nav className="flex flex-col gap-3">
              <a href="/dashboard" className="hover:text-gray-300">Dashboard</a>
              <a href="/products" className="hover:text-gray-300">Produtos</a>
              <a href="/categories" className="hover:text-gray-300">Categorias</a>
            </nav>
          </aside>

          {/* Conteúdo principal */}
          <main className="flex-1 overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
